// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAQAvWwwa3jakz5J7PzZLXUfQD_Zu8NoM',
    appId: '1:821717593480:web:1aeea97b31b7ed3ef79e3d',
    messagingSenderId: '821717593480',
    projectId: 'aplavankula',
    authDomain: 'aplavankula.firebaseapp.com',
    storageBucket: 'aplavankula.appspot.com',
    measurementId: 'G-3B8PMLG0VM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfYH5cPdNO4VzYBNelesbIbvcY91XxsS4',
    appId: '1:821717593480:android:3278991780b6c9b2f79e3d',
    messagingSenderId: '821717593480',
    projectId: 'aplavankula',
    storageBucket: 'aplavankula.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHc-nhb9oTpdk7N6deZtSxf-nPLkym9Rw',
    appId: '1:821717593480:ios:b57187b450dec606f79e3d',
    messagingSenderId: '821717593480',
    projectId: 'aplavankula',
    storageBucket: 'aplavankula.appspot.com',
    iosBundleId: 'com.example.clientApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDHc-nhb9oTpdk7N6deZtSxf-nPLkym9Rw',
    appId: '1:821717593480:ios:8f9dd7461d11f924f79e3d',
    messagingSenderId: '821717593480',
    projectId: 'aplavankula',
    storageBucket: 'aplavankula.appspot.com',
    iosBundleId: 'com.example.clientApp.RunnerTests',
  );
}
